#! /usr/bin/env ruby

at_exit do
  pids.each do |pid|
    Process.kill(:INT, pid)
  end

  Process.waitall
end

pids = []

# Masters
pids << spawn("redis-server --port 6380")
pids << spawn("redis-server --port 6381")

# Slaves of Master 1
pids << spawn("redis-server --port 63800 --slaveof 127.0.0.1 6380")
pids << spawn("redis-server --port 63801 --slaveof 127.0.0.1 6380")

# Slaves of Master 2
pids << spawn("redis-server --port 63810 --slaveof 127.0.0.1 6381")
pids << spawn("redis-server --port 63811 --slaveof 127.0.0.1 6381")

# Sentinels
pids << spawn("redis-server sentinel/sentinel.conf --sentinel --port 26379")
pids << spawn("redis-server sentinel/sentinel.conf --sentinel --port 26380")

Process.waitall
