# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

gem 'redis', path: File.expand_path("..", __dir__)
gem 'minitest'
gem 'rake'
gem 'rubocop', '~> 1.88.0'
gem 'mocha'

group :test do
  gem 'hiredis-client'
end
