source "https://rubygems.org"

gemspec :path => "../"

case ENV["conn"]
when "hiredis"
  gem "hiredis"
when "synchrony"
  gem "hiredis"
  gem "em-synchrony"
end

if RUBY_VERSION.to_f < 1.9
  gem 'test-unit', '3.1.5'
else
  gem 'test-unit', '>= 3.2.5'
end
