source "https://rubygems.org"

gemspec :path => "../"

# Using jruby-openssl 0.10.0, we get NPEs in jruby tests: https://github.com/redis/redis-rb/issues/756
platform :jruby do
  gem 'jruby-openssl', '<0.10.0'
end

case ENV["DRIVER"]
when "hiredis"
  gem "hiredis"
when "synchrony"
  gem "hiredis"
  gem "em-synchrony"
end

gem 'test-unit', '>= 3.2.5'
