# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

gem 'minitest'
gem 'rake'
gem 'rubocop', '~> 1.25.1'
gem 'mocha'
gem 'redis-cluster-client', github: 'redis-rb/redis-cluster-client'
